### ISSUE TITLE
support DDL statement "desc table"

### ISSUE THREAD

**Issue by jinmingjian** [tensorbase/tensorbase#103]

**Comment by abhikjain360** [comment]
Hi! I would like to work on this issue.

**Comment by jinmingjian** [comment]
@abhikjain360 Abhik, really thanks for your interests! This issue is good for understanding how the schema and meta side things works. And I would like to provide any help if you want.

**Comment by abhikjain360** [comment]
I wanted to confirm what all needs to be done.

I will first need to add ability to parse `desc table` in `lang` crate and then I will need to add function to run it in https://github.com/tensorbase/tensorbase/blob/main/crates/runtime/src/mgmt.rs#L189, and then finally ability to call it in https://github.com/tensorbase/tensorbase/blob/main/crates/runtime/src/mgmt.rs#L708 .
I am not missing any steps am I?

**Comment by jinmingjian** [comment]
@abhikjain360 basically, yes. This command is relatively trivial. 

From the view of CH, the output of ```desc table``` is a subset of ```show create table```, but **not the exact same**. 

```desc table``` just shows the column names and types. 

So, there are two ways for this command:
1.  extract infos from ```show create table```
2.  use [get_columns](https://github.com/tensorbase/tensorbase/blob/4288dbc5b4e5cc843368b25ff7d3922f7717bf62/crates/meta/src/store/sys.rs#L302) like apis. There are examples around the TB sources for this kind.
