### ISSUE TITLE
allow trailing semicolon in sql statement

### ISSUE THREAD

**Issue by jinmingjian** [tensorbase/tensorbase#107]

**Comment by chenyukang** [comment]
Let me have a try, do you have any references for this?

**Comment by jinmingjian** [comment]
@chenyukang thanks for interesting. Basically, this has been demonstrated in [bql.pest](https://github.com/tensorbase/tensorbase/blob/2e9165e7c990a5aee2c1b0486cfaf1bc314594c4/crates/lang/src/bql.pest#L10). You can try to add all cmds with "semicolon" to see if it is ok or not. If ok, you can try some alternative to shorten the grammar, some like(not tested):
```pest
cmd = {
    ... |
    cmd ~ (";")*
}
```
and make cmd_list shorter.

It is not hard and a great chnace to learn about pest and its grammar.

**Comment by chenyukang** [comment]
```rust
cmd = {
    ... | 
   cmd ~ (";")*
}
```
will trigger this compile error: 

```
error[E0599]: no function or associated item named `parse` found for struct `BqlParser` in the current scope
    --> crates/lang/src/parse.rs:1959:28
     |
19   | pub struct BqlParser;
     | --------------------- function or associated item `parse` not found for this
...
1959 |                 BqlParser::parse(Rule::cmd_list, c).unwrap_or_else(|e| panic!("{}", e));
     |                            ^^^^^ function or associated item not found in `BqlParser`
```

**Comment by jinmingjian** [comment]
@ygf11 ok, my bad memory, left recursion can not supported by pest. How about your original: 
```
one_cmd
cmd = {
   _{ one_cmd } ~ (";")*
}
```

**Comment by chenyukang** [comment]
> @ygf11 ok, my bad memory, left recursion can not supported by pest. How about your original, but like this:
> 
> ```
> one_cmd
> cmd = {
>    _{ one_cmd } ~ (";")*
> }
> ```

No, this is the same compile error.

**Comment by chenyukang** [comment]
https://github.com/tensorbase/tensorbase/pull/200/files
current PR passed tests.

**Comment by jinmingjian** [comment]
@chenyukang your PR mereged! Base thanks for your help!
