### ISSUE TITLE
Date and DateTime are not castable from utf8

### ISSUE THREAD

**Issue by jinmingjian** [tensorbase/tensorbase#108]
This should be the problem that TB has not enabled this conversion. It should be easy to fix. One similar is issue #98, but this is DF upstream problem.

**Comment by jinmingjian** [comment]
>  create table tt1(a Date) Engine=BaseStorage
insert into tt1 values ('2000-01-01')
select * from tt1 where a = '2000-01-01'

**Comment by whjpji** [comment]
I got this error
```
WrappingEngineError(WrappingDFError(Internal("Unsupported CAST from Utf8 to Date16"))). Internal error: Unsupported CAST from Utf8 to Date16. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker.
```

It seems that we need to modify DF's code to support this feature?

**Comment by jinmingjian** [comment]
Yes, Date and DateTime in TB is extended from DataFusion. Because these types are "non-standard" in Arrow spec. (Hint: For DataFusion's own Date, this query should work.)
