### ISSUE TITLE
more than 25000 lines change after cargo fmt

### ISSUE THREAD

**Issue by pymongo** [tensorbase/tensorbase#116]
My vscode and rust-analyzer setting is run `cargo fmt` after save

after fmt git diff is more than 25000 lines, Is tensorbase didn't `cargo fmt` for a long time?

```
[w@ww tensorbase]$ git diff --shortstat
 311 files changed, 15049 insertions(+), 10481 deletions(-)
```

When I try PR to tensorbase and fmt accidentally
cargo fmt cause more than 25000 lines and let tensorbase's reviewer hard to review PR(because too many lines change)

## My suggestions
1. make arrow-rs as a git submodule
2. exclude arrow-rs's dir on rustfmt.toml
3. add fmt to CI/CD/github check, run fmt on each commit/PR

sqlx and many rust projects has `cargo fmt` CI check on github PR, I think tensorbase also need this?

**Comment by jinmingjian** [comment]
@pymongo good idea! And thanks for this idea. I will check your idea recently. Remove out arrow-rs is in planning. And I will start this ASAP.

**Comment by pymongo** [comment]
I notice `Note: Recently, we [enforce code style via ```cargo fmt```](https://github.com/tensorbase/tensorbase/blob/main/docs/CONTRIBUTING.md#code-style).` was add to README.

But cargo fmt still has 70 lines change after this commit https://github.com/tensorbase/tensorbase/commit/47721db6c7fe514269746275e8bfce8dc00cc4df

```
[w@ww tensorbase]$ git checkout .
Updated 12 paths from the index
[w@ww tensorbase]$ cargo fmt
[w@ww tensorbase]$ git diff --stat
 crates/base/src/mem.rs                |  1 -
 crates/base/tests/proc_macro_tests.rs |  2 --
 crates/client/src/client.rs           |  4 +---
 crates/client/src/compression/mod.rs  |  6 ++----
 crates/client/src/protocol/decoder.rs |  9 ++++-----
 crates/engine/src/datafusions.rs      |  6 +++---
 crates/engine/tests/df_tests.rs       |  3 ---
 crates/meta/src/store/sys.rs          |  2 --
 crates/runtime/src/ch/blocks.rs       |  8 +++-----
 crates/runtime/src/ch/codecs.rs       |  5 -----
 crates/runtime/src/ch/messages.rs     | 28 ++++++++++++----------------
 crates/runtime/src/write.rs           |  3 +--
 12 files changed, 26 insertions(+), 51 deletions(-)
[w@ww tensorbase]$ git log -1
commit 53f2aa24e319c79500871dba45eb387080fc0e56 (HEAD -> main, upstream/main, origin/main, origin/HEAD)
Author: Jin Mingjian <jin.phd@gmail.com>
Date:   Mon Jun 28 22:05:00 2021 +0800

    tweak README
    
    Signed-off-by: Jin Mingjian <jin.phd@gmail.com>
```

**Comment by jinmingjian** [comment]
@pymongo thanks for reporting. Does the version of rustfmt affect this? I have not such problem.

**Comment by jinmingjian** [comment]
I forgot this issue, it is interesting to see ```cargo fmt``` are tracked here:)

**Comment by jinmingjian** [comment]
@pymongo confirmed. I am using the rustfmt 2.0 nightly. The behavior is different to that of rustup's 1.4.37. I will correct the source to the rustup's version.
