### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by ramondeklein** [tensorbase/tensorbase#15]
What is the status of this project? I only see an initial commit m0 and hardly any coding changes afterwards. Is this project terminated?

**Comment by jinmingjian** [comment]
@ramondeklein  thanks for interesting. The project and website will be updated in recent week. 

The plan is like this:

1. TensorBase Base Edition: this repo project of TensorBase will become TensorBase Base Edition. It is planned to provide a full Rust implementation in the Base edition, which will increase more engineering flexibility, lower latency and less performance (but still be faster than its peers in the open source world).
2. TensorBase Frontier Edition: there will be an alpha product of TensorBase Frontier Edition be released in the late of Feb (yeah, it will happen just in this month) as like a free software but without open source license. I will provide a new semi open source license to address the licensing dilemma between bigs and smalls, like recent re-licensing of Elasticsearch.

**Comment by jinmingjian** [comment]
the alpha site is out although the time is delayed a little:)
