### ISSUE TITLE
support CAST expression

### ISSUE THREAD

**Issue by jinmingjian** [tensorbase/tensorbase#158]
CAST expression: CAST(x AS t) is supported by DataFusion. But because (parsing and) type mismatching between DF and TB. Now the functionality can not work: 

```bash
select sum(cast(a as Int64)) from test_tab

SELECT sum(CAST(a, 'Int64'))
FROM test_tab

Query id: 2f373451-1ea2-4502-ba99-b6def83e457d


0 rows in set. Elapsed: 0.003 sec. 

Received exception from server (version 2021.5.0):
Code: 7. DB::Exception: Received from localhost:9528. WrappingEngineError(WrappingDFError(NotImplemented("Unsupported SQL type Custom(ObjectName([Ident { value: \"Int64\", quote_style: None }]))"))). This feature is not implemented: Unsupported SQL type Custom(ObjectName([Ident { value: "Int64", quote_style: None }])).
```

[more docs from CH](https://clickhouse.tech/docs/en/sql-reference/functions/type-conversion-functions/#type_conversion_function-cast)

**Comment by pandaplusplus** [comment]
Do a simple test on the latest version in DF that seems to only support it: 
     
`select sum(cast(a as int)) from test_tab`,

 there is an [issue](https://github.com/apache/arrow-datafusion/issues/81) about that, but only explicit casts between UINT and INT. Do you want to add a completed feature about type explicit casts? @jinmingjian

**Comment by jinmingjian** [comment]
@pandaplusplus thanks for pointing. I have not investigate deeply on this. My idea here is to allow up-cast cases: like Int32 to Int64. The Int64 in TB is named BIGINT in DF.  So this testcase can not pass.

For the future, we may help DataFusion on that general issue. Finally, TensorBase and DataFusion are one community. We will want to help them when we can help.

**Comment by pandaplusplus** [comment]
I see, Let me work it out.

**Comment by jinmingjian** [comment]
@pandaplusplus @whjpji @pymongo  thanks to all of your helps, Base have made rapid progress in many aspects recently! :rocket: :100: :pray: 

In this summer, several students will join our community. I will update a more detailed road map in the near future. I also hope that everyone can help these students. 

The completion of the summer milestone means that Base has a good shape and can better serve our basic users. In that time, we can compare with other open source data warehouses in this era, and even better. I am honored to participate in this journey with you all!

Finally, any question or fast message can be sent via my wechat account is: surfeitbj , or discord or slack or email(jin.phd at gmail.com) as well.

**Comment by pandaplusplus** [comment]
@jinmingjian Great! I love it when people help each other and see the Base community grow, it will be a very meaningful thing.
