### ISSUE TITLE
move to_date out from mix-up in DataFusion

### ISSUE THREAD

**Issue by jinmingjian** [tensorbase/tensorbase#159]
In #88, we mix to_date function impl into DataFusion. After #154, we have [dedicated CH mod](https://github.com/tensorbase/tensorbase/blob/main/crates/datafusion/src/physical_plan/clickhouse.rs). It is better to move to_date impl as ToDate in that mod.

**Comment by pandaplusplus** [comment]
I will fix it.

**Comment by jinmingjian** [comment]
@pandaplusplus thanks! No rush! Have a good night!

**Comment by jinmingjian** [comment]
it seems we have solved this issue in #173 !
