### ISSUE TITLE
Error compiling the master branch on macOS Catalina

### ISSUE THREAD

**Issue by lispking** [tensorbase/tensorbase#169]
% rustc --version
rustc 1.55.0-nightly (e6b4c252e 2021-06-25)

% cargo --version
cargo 1.55.0-nightly (9233aa06c 2021-06-22)

% cargo check
....
error[E0425]: cannot find function `mremap` in crate `libc`
   --> crates/base/src/mmap.rs:28:30
    |
28  |       let ret = unsafe { libc::mremap(addr, old_size, new_size, libc::MREMAP_MAYMOVE) };
    |                                ^^^^^^ help: a function with a similar name exists: `mmap`
    |
   ::: /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.97/src/unix/mod.rs:954:5
    |
954 | /     pub fn mmap(
955 | |         addr: *mut ::c_void,
956 | |         len: ::size_t,
957 | |         prot: ::c_int,
...   |
960 | |         offset: off_t,
961 | |     ) -> *mut ::c_void;
    | |_______________________- similarly named function `mmap` defined here

error[E0425]: cannot find value `MREMAP_MAYMOVE` in crate `libc`
  --> crates/base/src/mmap.rs:28:69
   |
28 |     let ret = unsafe { libc::mremap(addr, old_size, new_size, libc::MREMAP_MAYMOVE) };
   |                                                                     ^^^^^^^^^^^^^^ not found in `libc`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `base`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by jinmingjian** [comment]
@lispking this is just the issue #80

**Comment by jinmingjian** [comment]
we have no enough resource to support other platforms beyond Linux. If you know how to work with docker in your macos, then it is ok to build in a docker env.

**Comment by jinmingjian** [comment]
ok, I close this for favor #80
