### ISSUE TITLE
integ_test_timing test is perhaps too strict

### ISSUE THREAD

**Issue by fandahao17** [tensorbase/tensorbase#209]
While running the unit tests, I encountered this error.

```
test result: ok. 26 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 6.40s

     Running tests/proc_macro_tests.rs (target/debug/deps/proc_macro_tests-670e00d497cbb99d)

running 2 tests
test integ_test_str ... ok
test integ_test_timing ... FAILED

failures:

---- integ_test_timing stdout ----
t0: 10.575744ms
22.260992ms
thread 'main' panicked at 'assertion failed: (t1.elapsed() - ten_millis - ten_millis) < time::Duration::from_millis(1)', crates/base/tests/proc_macro_tests.rs:19:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    integ_test_timing

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s
```

The error happens in this line.

``` rust
assert!((t1.elapsed() - ten_millis - ten_millis) < time::Duration::from_millis(1));
```

From the stdout, I suspect the failure is because we let the the thread sleep for 20ms and check that the timer indeed reports that time has passed 20 ms. In my case the time passed 22.260992ms, which does not seem very bad. However, because we only tolerate 1ms error, the test mistakenly reported failure.

After changing the limit from 1ms to 5ms, the test passed. Maybe we can use a more loose limit such as 5ms?

**Comment by jinmingjian** [comment]
@fandahao17 possible. Welcome to sent out a PR for this. It is OK to relax this best-effort kind testcase.
