### ISSUE TITLE
support max/min/avg aggregation

### ISSUE THREAD

**Issue by jinmingjian** [tensorbase/tensorbase#3]

**Comment by waahm7** [comment]
Hi, I would like to work on this issue. I am new to Rust and would love to get some mentorship.

**Comment by jinmingjian** [comment]
Hi, @waahm7. Very appreciated for your interests. 

1. Firstly, you may need to be familiar with the Rust. There are countless materials on the web. If you are nice at C like system language, I think the learning curve is straight. A little more recommendations for old-men-from-c-or-cpp-world: [Rust For Systems Programmers](https://github.com/nrc/r4cppp), [Rust Language Cheat Sheet](https://cheats.rs/) for quick checking-at-hand. 

2. To get familiar the [tools which are used in the Base](https://github.com/tensorbase/tensorbase/blob/master/docs/dev.md#tools-recommendation). If you reach here, we may schedule some remote meeting for some quick project review/help. Feel free to get me at [Base slack channel](https://join.slack.com/t/tensorbase/shared_invite/zt-gi2kgx9s-h7IPxc0fdo9h2EvtbLis~w) for more realtime feedback.

3. Understand the basic work flow for Base runtime engine. Just simple: 
Input -> SQL Parsing -> IR building ( multi-level abstractions and optimizations, but now it is easy-understanding) -> Kernel codegen (gen executable C code) -> Kernel running (Via a JIT library, now is a blackbox dll) -> Result responding and showing.

4. For this issue, it is a little easier in that there a sum aggregation as an example. So, you should firstly try to see if you can understand how the sum aggregation done in Base. The core of sum agg is just [an embedded c template](https://github.com/tensorbase/tensorbase/blob/beb4f4cf6cbcbdca62c93e63fc9b9bf1c681f4be/crates/ir/src/codegen.rs#L128). 
Here, Base maps the query pipeline semantics into a c semantics directly, which guarantees a top-performance and human-debuggable sql execution. The neat gen output can be directly checked and executed with a standalone c compiler via [a simple c runner](https://github.com/tensorbase/tensorbase/blob/master/crates/runtime/ker_lib/ker_runner.c) (current ker_runner.c is just showing the sum agg's gen). 
So, to resolve this issue, it is just enough to tweak that template around to gen some suitable c codes according to the operators.

**Comment by waahm7** [comment]
@jinmingjian Thanks a lot for providing helpful links. I tried to join the slack channel but it says this link is no longer active. Can you please give me a new link?

**Comment by jinmingjian** [comment]
@waahm7 I am new to the slack:) It seems that the link has been expired. Sorry. Try [this link](https://join.slack.com/t/tensorbase/shared_invite/zt-h1uqloyu-DG6kMOEYedEIbakImUkvSA) and I've invited your gmail into the channel.

**Comment by jinmingjian** [comment]
the problem fixed in TensorBase Frontier. this TensorBase repo is restarting as TensorBase BE.
