### ISSUE TITLE
link is really slow when building tensorbase

### ISSUE THREAD

**Issue by sundy-li** [tensorbase/tensorbase#41]
Building tensorbase may cost 5 ~ 6 minutes for linking.

```
    Building [=======================> ] 332/333: server(bin)
```

**Comment by jinmingjian** [comment]
@sundy-li yes if release building may cause by [the lto opt](https://github.com/tensorbase/tensorbase/blob/main/Cargo.toml)

**Comment by jinmingjian** [comment]
you can just leave the opt-level = 3 and remove others when developing. Let's do some performance tests to see if it is ok to relax this configs.

**Comment by jinmingjian** [comment]
The performance degrade without lto is huge for complex aggregations(~30%). 

lto='thin' seems as a balance, which is relatively fast and only incur 10-15% degradation.
