### ISSUE TITLE
JDBC Driver Connection Times Out on Read

### ISSUE THREAD

**Issue by chrisfw** [tensorbase/tensorbase#81]
@jinmingjian ,  Jin, I attempted to connect to the TB server using the Clickhouse JDBC driver (pulled in by DBeaver) on port 9528, but the connection attempt times out on the read.  I tried configuring the connection properties both with no Database/Schema specified as well as with **default**.  I also tried with the **No authentication** option set.  Below are screen captures illustrating the connection properties and the connection error.  Note that I also confirmed that the firewall is turned off.

![clickhouse-jdbc-conn](https://user-images.githubusercontent.com/6135741/118000330-ba859800-b313-11eb-83db-9fcb2dfce008.png)

![clickhouse-jdbc-conn-error](https://user-images.githubusercontent.com/6135741/118000369-c1aca600-b313-11eb-86a2-ecbd120f2d7e.png)

**Comment by chrisfw** [comment]
@jinmingjian , I see now that I should have tested with the Native driver you linked as it is not the official one.  I will retest with that one.

**Comment by jinmingjian** [comment]
@chrisfw thanks for reporting. You are right. The official JDBC driver is based on another HTTP protocol, which has not been supported by TensorBase now.
