### ISSUE TITLE
Clickhouse-Native-JDBC-Driver connection attempt throws Unsupported Client Version exception

### ISSUE THREAD

**Issue by chrisfw** [tensorbase/tensorbase#82]
Utilizing the latest version of the Clickhouse-Native-JDBC driver available from Maven (2.5.4), I attempted to connect to TB, but an unsupported client version exception is thrown.

![clickhouse-native-driver-conn](https://user-images.githubusercontent.com/6135741/118016293-3b985b80-b323-11eb-8861-620ad25e3e1a.png)

![clickhouse-native-jdbc-error](https://user-images.githubusercontent.com/6135741/118016502-77cbbc00-b323-11eb-95c1-2db382a749dd.png)

@jinmingjian Jin, please let me know if you would also like me to try testing programmatically via Java code directly.

**Comment by jinmingjian** [comment]
@chrisfw  thanks for reporting. Good catch! It seems jdbc client version is too high:)

**Comment by jinmingjian** [comment]
For today's investigation, the CH-Native-JDBC-Driver shows significantly different to other client's behavior. So, it is decided to implement a HTTP protocol support (in issue #90 ) rather than enable this 3rd-party driver. @chrisfw thanks for your testing help!
