### ISSUE TITLE
[RFC]Support Builtin functions with Datafusion

### ISSUE THREAD

**Issue by DallasC** [tensorbase/tensorbase#84]
The easiest way to support builtin functions seems to be by using [ScalarUDF](https://docs.rs/datafusion/4.0.0/datafusion/physical_plan/udf/struct.ScalarUDF.htmll) or [AggregateUDF](https://docs.rs/datafusion/4.0.0/datafusion/physical_plan/udaf/struct.AggregateUDF.html).

## Changes
To support this the following changes would have to be made

### `lightjit::builtins`
We have to convert the functions into type `datafusion::ScalarUDF`.

Also, add a `get_udf()` function that matches a string to the function.

Should we still have these located here or maybe move them into a different crate?

### `lang::parse`
add a new function `parse_builtins(p)`. This would be similar to the current `parse_tables(p)` function but look for any builtins and return a `HashSet` of the ones found.

### `engine::run()`
add `let builtins = parse::parse_builtins(p)?;`. We would have to also add this field to `datafusion::run` the same as `tabs` or `cols`.

``` Rust
    let (tabs, cols) = parse::parse_tables(p)?;
    let builtins = parse::parse_tables(p)?; // <--- New
    log::debug!("projections - tabs: {:?}, cols: {:?}", tabs, cols);
    datafusions::run(ms, ps, current_db, raw_query, query_id, tabs, cols, builtins, qs) // <- also pass builtins
```

### `engine::datafusion::run()`
Before running we can check the `sql` if any builtins are used. If used all we need is to `cxt.register_udf(builtin)`.

Sudo code 
``` Rust
let mut ctx = ExecutionContext::new();
...
if !builtins.is_empty() {
    for f in builtins.drain() {
        let udf = get_udf(f)?;
        ctx.register_udf();
    }
}
let df = ctx.sql(raw_query)?;
...
```

**Comment by jinmingjian** [comment]
@DallasC This is a great reading for current UDF additions. I promote this issue to RFC.  DataFusion in fact, has lots of builtins, but which are not same to those of ClickHouse in naming. 

Could you add some alias builtins to allow ClickHouse to work without changes according to your proposed this RFC?

**Comment by jinmingjian** [comment]
> Before running we can check the sql if any builtins are used.
In the future, we may change this behaviors. Because the runtime cost for register UDF makes no much sense. It is ideal to enable preloading mechanism although this may need to change to DataFusion.

**Comment by DallasC** [comment]
Yeah adding aliases would be easy I think. Datafusion currently just has some `math` and `string` functions so for things like `dates` and `intervals` we would have to use UDFs

All the functions are located at `arrow-datafusion/datafusion/src/physical_plan/functions.rs`. We just have to find out what ones differ from the [clickhouse functions](https://clickhouse.tech/docs/en/sql-reference/functions/).

**Comment by DallasC** [comment]
I agree the extra runtime cost isn't ideal. I looked a little more but from what I can tell there isn't a way to preload  UDFs in DF currently.  I'm not sure how difficult this would be to add. 

Adding the builtins directly to DF could be a short-term alternative without any performance drawbacks just to get Tpch fully running. It's pretty easy to do but a little verbose.  

After we finish up tpch fully, I can revisit this and get preloading working.

**Comment by jinmingjian** [comment]
We now use a hooking way to provide Base customized builtins in Datafusion introduced with #154. The method is a little intrusive but simpler and faster. I close this issue. If there are more problem, we track them in other issues.  Finally, thanks @DallasC for such great RFC!
