### ISSUE TITLE
Cannot join slack channel from the links in README or in offcial website, maybe consider opening a new communication channel like gitter?

### ISSUE THREAD

**Issue by BIAOXYZ** [tensorbase/tensorbase#9]
When click the `Slack Channel` link in README or in official website, it redirects you to tensorbase's official Slack Channel link: https://tensorbase.slack.com/, but without an invitation. So I think newcomers cannot log in. 
![image](https://user-images.githubusercontent.com/6740021/89734076-56842980-da8c-11ea-8c3f-d15d0021a3fb.png)

I can log in other slack workspaces like Kubernetes, so I guess it's just because tensorbase's slack link is not an invitation link. See that of k8s', there is a button says "GET MY INVITE" for people who are not in the group.
![image](https://user-images.githubusercontent.com/6740021/89734157-f04bd680-da8c-11ea-8c4a-a49d4bf200de.png)

**Comment by jinmingjian** [comment]
@BIAOXYZ  much thanks for your feedback! just back from a leave! Let me do a check. I am sure that we need a big bang of talking way...

**Comment by jinmingjian** [comment]
@BIAOXYZ you are right. I've found the invitation link ... I have done a change to the slack link. Can you give a try to confirm? It is truly a shame that we can not design the communication in high availability :smile: 

**Base thanks for your help!**

**Comment by BIAOXYZ** [comment]
@jinmingjian After my try, I am sure it's Okay now.

When click the link from official website (pls note that the link in README might also needs to be fixed):
![image](https://user-images.githubusercontent.com/6740021/89735198-64897880-da93-11ea-9415-a84da6713ead.png)

Actually I have already joined, thanks.
![image](https://user-images.githubusercontent.com/6740021/89735265-d5c92b80-da93-11ea-91d5-9cff5118bc47.png)

**Comment by jinmingjian** [comment]
Yeah! Welcome to Base! :tada:

**Comment by compasses** [comment]
so now it's not work again:
![image](https://user-images.githubusercontent.com/10161171/102954781-45a1f500-450f-11eb-9b64-97025a16956c.png)

maybe you can create a wechat group :)

**Comment by jinmingjian** [comment]
@compasses thanks for reporting. Let me do a update!

**Comment by jinmingjian** [comment]
update done!
