### ISSUE TITLE
[piece-of-cake-this-week]Error while handling a SQL end with a semicolon

### ISSUE THREAD

**Issue by Thysinner** [tensorbase/tensorbase#91]
### 1. Minimal reproduce step (Required)

```sql
create table employees (id UInt64, salary UInt64) ENGINE = BaseStorage
insert into employees values (0, 1000), (1, 1500)
```

```sql
select count(id) from employees;
```

### 2. What did you expect to see? (Required)

With ClickHouse server and ClickHouse client:
```sql
debian :) select count(id) from employees;

SELECT count(id)
FROM employees

┌─count(id)─┐
│         2 │
└───────────┘

1 rows in set. Elapsed: 0.004 sec.
```

```sql
debian :) select count(id) from employees

SELECT count(id)
FROM employees

┌─count(id)─┐
│         2 │
└───────────┘

1 rows in set. Elapsed: 0.002 sec.
```

### 3. What did you see instead (Required)

With TensorBase server and ClickHouse client:
```sql
TensorBase :) select count(id) from employees;

SELECT count(id)
FROM employees

Received exception from server (version 2021.5.0):
Code: 3. DB::Exception: Received from 0.0.0.0:9528. WrappingLangError(ASTError). Error when AST processing.

0 rows in set. Elapsed: 0.008 sec.
```

```sql
TensorBase :) select count(id) from employees

SELECT count(id)
FROM employees

┌─COUNT(id)─┐
│         2 │
└───────────┘

1 rows in set. Elapsed: 0.011 sec.
```

### 4. What is your TensorBase version? (Required)

`version 2021.5.0 revision 54405`

**Comment by jinmingjian** [comment]
@ThySinner thanks for your good formal issue reporting! This could be seen a bug if we want to support multiple statements in one line. But if we only support a statement in console. This is just a style problem. I just leave this issue here to see if these is necessary for other users.

**Comment by ThySinner** [comment]
We could lable the issue as a low priority.

**Comment by jinmingjian** [comment]
IMHO, this is easy to fix. Not sure if one want to have a try:)
