### ISSUE TITLE
Type incoherent in comparison of `String` type with a string literal

### ISSUE THREAD

**Issue by whjpji** [tensorbase/tensorbase#98]
As I was implementing #53, I found an error that also occurred in `String` type.

After executing the following SQL,
```sql
create table test (s String) engine = BaseStorage
insert into test values ('test')
select s from test -- returned a single row 'test'
select s from test where s = 'test' -- error occurs here!
```
I received this error,
```
Received exception from server (version 2021.5.0):
Code: 7. DB::Exception: Received from localhost:9528, ::1. WrappingEngineError(WrappingDFError(Plan("'LargeUtf8 = Utf8' can't be evaluated because there isn't a common type to coerce the types to"))). Error during planning: 'LargeUtf8 = Utf8' can't be evaluated because there isn't a common type to coerce the types to.
```

After some analysis, I found TB's query is executed in DataFusion, and accidentally, `String` type in TB is translated to Arrow's `LargeUtf8`, but the string literal seems to be parsed as the type `Utf8`, which is incoherent with `LargeUtf8`.

Yet I have few ideas of how to fix this issue. Maybe we should modify the implementations in DataFusion?

**Comment by jinmingjian** [comment]
@whjpji thanks for your reporting. Yes. This is DF's problem. The best way is to make utf8 castable to largetuft8 or similar.

**Comment by jinmingjian** [comment]
In fact, this problem is tricky. The largerutf8 and utf8 is castable, but not enable in the planner. And more TB' string is a little different to the Arrow's string. So, to solve this problem, we need two fixs in one...
